Hometask 2
KatyaKlema/smart-home-2020 pull request #2
Opened 2020-03-21 09:09 UTC by KatyaKlema

2020-03-23 13:49 UTC, a-ivanov requested changes

2020-03-23 13:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +    public void init(SmartHome smartHome);
Разве действие инициализирует дом (судя по вашему названию)?

2020-03-23 13:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        while (eventTemp.getEvent() != null) {
Это поправить по 1 дз.

2020-03-23 13:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorIterator.java
> +public class DoorIterator implements Iterator<Event> {
По 2 дз не должно быт никаких итераторов, тут нужен внутренний итератор http://bit.ly/2U6PHMN

2020-03-23 13:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Event.java
> +    private static SensorEvent event;
В чем отличие Event и SensorEvent и RandomEvent? По заданию есть события и генератор событий. Причем в случае этого проекта, имплементация генератора - это создавать случайным образов одно из возможных событий для двери, света, итд.
Сделайте один класс события и добавьте в него поле Enum, к кому это событие относится (дверь/свет/...).

2020-03-23 13:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Processor.java
> +public interface Processor<T> {
Уберите дженерики, тут они не нужны. Для обработки события достаточно класса самого события. Т.е. сигнатура метода обработки может выглядеть так: void handle(SensorEvent event). Каждый обработчик в свою очередь может имплементировать этот интерфейс и сделать что-то с событием, например, запустить Action в SmartHome. SmartHome для этого имплементирует интерфейс Actionable.

2020-03-23 13:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/PrintSmartHomeComponents.java
> +public interface PrintSmartHomeComponents<T, K> {
Это не нужно, просто логируйте событие внутри обработчика.

2020-03-23 13:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventTypeDoor.java
> +public enum SensorEventTypeDoor{
Объедините в одно с SensorEventTypeLight, так вам приходится нарушать OCP.

2020-03-27 08:31 UTC, a-ivanov requested changes

2020-03-27 08:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        List<Processor> processors = Arrays.asList(new LightEventProcessor(smartHome), new DoorEventProcessor(smartHome));
А где обработчик события с закрывающейся дверь в гостиной из 1 дз?

2020-03-27 08:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventProcessor.java
> +            for ( Room room : smartHome.getRooms() ) {
Замените на внутренний итератор http://bit.ly/2U6PHMN во всех обработчиках

2020-04-25 10:40 UTC, a-ivanov requested changes

2020-04-25 10:40 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_components/SmartHome.java
> +        action.execute(this);
Где действия над `Collection<Room> rooms`?

2020-04-25 10:40 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_components/Room.java
> +        action.execute(this);
Где действия над `Collection<Light> lights` и `Collection<Door> doors`?

2020-04-25 10:40 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_components/Light.java
>  public class Light {
Почему не имплементит `Actionable`? Как над ним совершать действия?

2020-04-25 10:40 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_components/Door.java
>  public class Door {
Почему не имплементит `Actionable`? Как над ним совершать действия?

2020-04-25 11:02 UTC, a-ivanov requested changes

2020-04-25 11:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        JSONData tempJSON = new JSONData("smart-home-1.js");
Перенесите создание дома в отдельный класс, чтобы было `SmartHome smartHome = homeReader.read("home.json")` без `IOException`.

2020-04-30 07:13 UTC, a-ivanov requested changes

2020-04-30 07:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_components/SmartHome.java
> +        action.execute(this);
Не сделано.

2020-04-30 07:13 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_readers/JSONHomeReader.java
> +    public SmartHome read(String addr) throws IOException {
Как уже писал, уберите `throws IOException`, это leaky abstraction.

2020-05-04 06:46 UTC, a-ivanov approved these changes

2020-05-04 06:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_components/SmartHome.java
> +        rooms.forEach(room->room.execute(action));
Тут еще можно добавить строку, где Action выполняется над самим SmartHome.

2020-05-04 06:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/home_components/Room.java
> +        for (Light light : lights){
Тоже можно Room передавать в Action.

2020-05-04 15:53 UTC, closed without merging

2020-05-04 15:53 UTC, KatyaKlema commented
Homework 2 done