Hometask 3
KatyaKlema/smart-home-2020 pull request #3
Opened 2020-03-21 17:10 UTC by KatyaKlema

2020-03-23 14:02 UTC, a-ivanov requested changes

2020-03-23 14:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Alarm.java
> +    public void setAlarmState(Integer code, AlarmState alarmState){
Разве проверка кода - это не ответственность состояния, которое пытаются сменить попыткой ввода кода?

2020-03-23 14:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Alarm.java
> +    private final Integer code;
Почему boxed Integer, а не int?

2020-03-23 14:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Alarm.java
> +    public Integer getCode(){
Т.е. я как клиент могу вот так вот легко узнать секретный код и отключить сигнализацию?

2020-03-23 14:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmState.java
> +    protected AlarmStateType alarmStateType;
Так не надо, сделайте по классу на каждое состояние. Такой интерфейс можете оставить. Там нужно всего три метода: отключить сигнализацию, включить сигнализацию, перевести сигнализацию в активный режим (см. детали в описании дз).

2020-03-23 14:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/TriggerAlarmEventProcessor.java
> +    private boolean isDoor(Event event){
Это все как и isLight - нарушение OCP, уберите эту логику.

2020-03-23 14:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        TriggerAlarmEventProcessor triggerAlarmEventProcessorLight = new TriggerAlarmEventProcessor(smartHome, new LightEventProcessor(smartHome));
Помните, что надо сделать так, чтобы отправлялось всего 1 смс https://bit.ly/2UoOLDs

2020-03-23 14:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorInformation.java
> +public class DoorInformation {
Это лишний класс, перенесите всю логику определния соыбтия и его обработки в класс HallDoorEventProcessor. То же самое для двери и света.

2020-03-27 08:41 UTC, a-ivanov requested changes

2020-03-27 08:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventProcessor.java
> +        if ( event.getSensorEvent().getType() == DOOR_CLOSED) {
Надо использовать внутренний итератор.

2020-03-27 08:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Handler.java
> +public interface Handler {
Удалите неиспользуемые классы.

2020-03-27 08:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeData.java
> +    public T getData() throws IOException;
leaky abstracton из 1 дз.

2020-03-27 08:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/TriggerAlarmEventProcessor.java
> +        return event.getSensorEvent().getType() == SensorEventType.DOOR_OPEN || event.getSensorEvent().getType() == SensorEventType.DOOR_CLOSED
Это нарушение OCP. Уйдите от этих явных проверок.

2020-03-27 08:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmState.java
> +    protected AlarmStateType alarmStateType;
См. пример, как имплементировать шаблон состояние https://refactoring.guru/ru/design-patterns/state

2020-03-27 08:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmState.java
> +    public abstract void ALARM_TRIGGER();
Методы camelCase http://bit.ly/3cVontB

2020-03-27 08:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmState.java
> +    protected AlarmStateType alarmStateType;
Старайтесь не использовать абстрактные классы. Используйте интерфейсы (см. плюсы и минусы Efective Java, Item 20).

2020-04-01 10:24 UTC, KatyaKlema commented on src/main/java/ru/sbt/mipt/oop/AlarmState.java
> +    protected AlarmStateType alarmStateType;
А там состояния итак разбиты по классам: ActivateState, DeactivateState, TriggerState. И все эти типы состояний как раз расширяют мой основной класс AlarmState. Так что там все хорошо

2020-04-06 14:35 UTC, a-ivanov commented
Судя по https://github.com/KatyaKlema/smart-home-2020/pull/4/files и https://github.com/KatyaKlema/smart-home-2020/pull/5/files там более актуальный код, поэтому комментарии по 1-3 дз буду писать там.

2020-04-25 10:53 UTC, a-ivanov requested changes

2020-04-25 10:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart_home/Handler.java
> +public interface Handler {
Что это за интерфейс без методов? Зачем он нужен? Можно удалить.

2020-04-25 10:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/alarm/AlarmState.java
> +    public void ignore(){
Уберите этот метод, такого по заданию не было.

2020-04-25 10:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        TriggerAlarmEventProcessor triggerAlarmEventProcessorDoor = new TriggerAlarmEventProcessor(smartHome, new DoorEventProcessor(smartHome));
Как классы `TriggerAlarmEventProcessor` и `TriggerAlarmEventProcessor` связаны с `SmartHomeHandler`?
Они же сейчас работают с собственными `DoorEventProcessor` и `LightEventProcessor`, а должны с процессорами в `SmartHomeHandler`.

2020-04-30 07:20 UTC, a-ivanov requested changes

2020-04-30 07:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/processors/TriggerAlarmEventProcessor.java
> +    public void processing(SensorEvent event){
Поставьте `@Override` аннотацию для имплементации метода интерфейса.

2020-04-30 07:20 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        List<Processor> processors = Arrays.asList(new LightEventProcessor(smartHome), new DoorEventProcessor(smartHome),
Уже лучше. Но опять, уберите `new LightEventProcessor(smartHome), new DoorEventProcessor(smartHome)`, они уже созданы внутри `TriggerAlarmEventProcessor`. Они не будут останавливаться при активной сигнализации.
Перенесите `new HallDoorEventProcessor(smartHome)` внутрь `TriggerAlarmEventProcessor`, чтобы он тоже останавливался.

2020-04-30 11:28 UTC, a-ivanov requested changes
Не делайте реквест на проверку, когда не до конца поправили все предыдущие замечания https://github.com/KatyaKlema/smart-home-2020/pull/3#discussion_r417804891.

2020-05-04 06:55 UTC, a-ivanov approved these changes

2020-05-04 06:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/processors/TriggerAlarmEventProcessor.java
> +            ret = ret || (fixedType == sensorEventType);
Зачем нужно `ret = ret`? Выглядит, как опечатка, поскольку тут присваивается `ret` в `ret`, а не сравнивается.

2020-05-04 06:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/processors/TriggerAlarmEventProcessor.java
> +            ret = ret || (fixedType == sensorEventType);
Во-вторых, поскольку `SensorEventType` enum, то в `event.getType()` не может быть каких-либо значений, отличных от тех, что перечислены в `SensorEventType`. Поэтому тут проверять, что пришел правильный тип не надо, это делает Java.

2020-05-04 15:54 UTC, KatyaKlema commented
Homework 3 is done

2020-05-04 15:54 UTC, closed without merging